### ISSUE TITLE
/data files not found even when media paths or mounted

### ISSUE THREAD

**Issue by IssacI19** [stevezau/plex_generate_vid_previews#90]
I just figured it would be better if this were its separate thing. I finally got the Docker container to work, but now I keep getting an error that it cannot find my files and just skips them entirely. Here's my setup.

My media is in a directory that is `/mnt/tank/media`. In my Plex container, I just pointed `/mnt/tank/media` as a mount in the container and pointed to my movies and TV show folders in Plex directly. 

<img width="1061" height="612" alt="Image" src="https://github.com/user-attachments/assets/d55e9048-d6d1-4b93-916c-d5b211b48e87" />

In my plex_generate_vid_previews compose file, im binding `/mnt/tank/media:/data` to the container

<img width="421" height="56" alt="Image" src="https://github.com/user-attachments/assets/244f3078-0ba1-4682-9017-5020831da6c2" />

But still im getting logs saying that `/data/movies` or `/data/tv-shows` aren't found. I attached my actual Docker Compose file. Any thoughts on this?

<img width="877" height="1078" alt="Image" src="https://github.com/user-attachments/assets/3bab0da8-9598-4b0e-a821-d2d90d267d44" />

<img width="892" height="1062" alt="Image" src="https://github.com/user-attachments/assets/76e68183-32d2-4937-8e98-d5d45dfe4058" />

```
version: '3'
services:
  plex_generate_vid_previews:
    image: stevezzau/plex_generate_vid_previews:latest
    user: 1000:1000 
    environment:
      - PLEX_URL=http://192.168.1.69:32400/
      - PLEX_TOKEN=<my-plex-token>
      - PLEX_BIF_FRAME_INTERVAL=5
      - THUMBNAIL_QUALITY=4
      - PLEX_LOCAL_MEDIA_PATH=/mnt/apps/configs/plex/config/Library/Application Support/Plex Media Server/Media
      - TMP_FOLDER=/tmp/previews
      - PLEX_TIMEOUT=300
      - REGENERATE_THUMBNAILS=true
      - LOG_LEVEL=debug
      - DEBUG=true
      - GPU_THREADS=5  
      - CPU_THREADS=5
    volumes:
      - /mnt/apps/configs/plex/config/Library/Application Support/Plex Media Server/Media:/mnt/apps/configs/plex/config/Library/Application Support/Plex Media Server/Media/localhost
      - /mnt/tank/media:/data
    devices:
      - /dev/dri:/dev/dri
    command: ["/bin/sh", "-c", "ls -al /mnt/apps/configs/plex && sleep 600"]
```

**Comment by stevezau** [comment]
@IssacI19 I have completely rewritten the script. Can you try version 2.0?

There are breaking changes, mainly the env PLEX_LOCAL_MEDIA_PATH  has changed to PLEX_CONFIG_FOLDER which should point to the plex config folder now.

**Comment by issaci22** [comment]
Oh great I'm out of town and I'll download it when I get back

**Comment by stevezau** [comment]
ok thanks please lmk

**Comment by issaci22** [comment]
Hey man, I finally got back and Im trying to install the script, but Im still getting an error when I try to run it.

<img width="1428" height="565" alt="Image" src="https://github.com/user-attachments/assets/09eea5bb-b820-43e0-b46a-7b0c887aad5a" />

Here's the Docker compose that im using now
```
version: '3.8'
services:
  previews:
    image: stevezzau/plex_generate_vid_previews:latest
    user: 568:568
    environment:
      - PLEX_URL=http://192.168.1.69:32400
      - PLEX_TOKEN=<Plex token>
      - PLEX_CONFIG_FOLDER=/config/plex/config/Library/Application Support/Plex Media Server
    volumes:
      - /mnt/apps/configs/plex/config/Library/Application Support/Plex Media Server:/config/plex
      - /mnt/tank/media:/media
    devices:
      - /dev/dri:/dev/dri
```
I try using the LOG_DEBUG=debug, but either im using it wrong or something, but everytime I try to run it like that, it says it's an invalid YAML file, so I don't know if I can debug it. Any thoughts?

**Comment by stevezau** [comment]
@IssacI19 where does it say invalid YAML file? All you need to do is add

    environment:
      - LOG_LEVEL=DEBUG

However, the error you are receiving is clearly stating the problem. I am not sure if you are actually reading the log. It says the folder "/config/plex/config/Library/Application Support/Plex Media Server" does not exist in your container. 

You set the env var PLEX_CONFIG_FOLDER to "/config/plex/config/Library/Application Support/Plex Media Server"

However, you mounted "/mnt/apps/configs/plex/config/Library/Application Support/Plex Media Server" to /config/plex. 

So you need to edit PLEX_CONFIG_FOLDER to point to  /config/plex

Does that make sense?

**Comment by issaci22** [comment]
Yes let me try that now

**Comment by issaci22** [comment]
Ok now it's working however I'm getting more issues now I think and I don't know what this means 😭

https://github.com/user-attachments/assets/e7ddf551-9cbd-4f8d-8f60-775894e2403f

**Comment by stevezau** [comment]
What GPU do you have on this system where the container is running.?

**Comment by issaci22** [comment]
So the /dev/dri is my Intel Arc GPU. That's what's passing through to th container

**Comment by stevezau** [comment]
this is a bug. fixing it. give me 10

**Comment by stevezau** [comment]
I just pushed a new version.. can you try ? You'll need to redownload the latest tag.

**Comment by issaci22** [comment]
Still getting the same error with it. Apparently, it looks like it's seeing it, but it's not using it, I guess. I don't have FFMPEG installed on my TrueNAS system because I don't know how to install it on TrueNAS without using the `apt` command. Worst comes to worst, I can set the `GPU_THREADS=0` so I can use my CPU, but I want to try and use my GPU as well because I don't know how intensive this is on my GPU.

<img width="641" height="1066" alt="Image" src="https://github.com/user-attachments/assets/d106b9f6-c4ea-4992-a221-b0bb1068865b" />

**Comment by stevezau** [comment]
can you trty agian with the latest version.. i think i found some bugs

**Comment by issaci22** [comment]
Hey so I finally got it working. Now, is there a way for me to se a progress bar and the name of the file it's generating, cause all im seeing now is this.
Maybe, as a suggestion, at the bottom of the logs there could be a progress bar and the file/location name at the top for what's currently being created (Example of name `/data/movies/<movie name>`)

<img width="943" height="1067" alt="Image" src="https://github.com/user-attachments/assets/88e62074-a809-4a5d-a61f-d7e78d3d8628" />

**Comment by issaci22** [comment]
Or maybe like how Plex does it in their logs. it just updates texty in the log files, saying what percentage it's at.

**Comment by stevezau** [comment]
@IssacI19 great.. Yes there already is progress bar.. if you do a docker logs -l <container name> in the terminal you should see it. The progress does not show for you as i think you are reading the unraid container log output. 

I pushed a new change to dev.. try again.. 


```
2025/10/16 09:38:30 | ℹ️  - Processing 10742 items with 1 workers
2025/10/16 09:38:30 | ℹ️  - [GPU 0]: Started processing A Video
2025/10/16 09:38:31 | ℹ️  - [GPU 0]: A Video - 0% (speed=0.0x)
2025/10/16 09:38:36 | ℹ️  - [GPU 0]: A Video - 99% (speed=0.0x)
2025/10/16 09:38:36 | ℹ️  - Generated Video Preview for A Video.mkv HW=True TIME=5.0seconds SPEED=999x
```

Test it with

image: stevezzau/plex_generate_vid_previews:dev

**Comment by issaci22** [comment]
I did LOG_LEVEL=verbose, and I got an error saying it's either debug, info, critical, error, or warning. For me, "verobes" isn't an option. Should I just leave it on debug and do it in the shell, or is one of the options the right one?

<img width="845" height="307" alt="Image" src="https://github.com/user-attachments/assets/6b82c184-7307-4137-95de-a51a15de6958" />

**Comment by issaci22** [comment]
> image: stevezzau/plex_generate_vid_previews:dev

Oh I see this now

**Comment by stevezau** [comment]
Yes ignore verbose, i decided to not go with that approach, it should just work with info

**Comment by issaci22** [comment]
on the stable release or the dev?

**Comment by stevezau** [comment]
dev for now

**Comment by issaci22** [comment]
ok, i see now. But at one point, are you going to make it so it looks like this when in action? Like how in FFMPEG it's always at the bottom and not just a list that updates the logs. Is that going to be "verbose" in a later version?

> ```
> 2025/10/16 09:38:30 | ℹ️  - Processing 10742 items with 1 workers
> 2025/10/16 09:38:30 | ℹ️  - [GPU 0]: Started processing A Video
> 2025/10/16 09:38:31 | ℹ️  - [GPU 0]: A Video - 0% (speed=0.0x)
> 2025/10/16 09:38:36 | ℹ️  - [GPU 0]: A Video - 99% (speed=0.0x)
> 2025/10/16 09:38:36 | ℹ️  - Generated Video Preview for A Video.mkv HW=True TIME=5.0seconds SPEED=999x
> ```

**Comment by stevezau** [comment]
@IssacI19 what do you mean?

**Comment by issaci22** [comment]
from this.

<img width="678" height="1083" alt="Image" src="https://github.com/user-attachments/assets/8c5fd0be-8b98-4603-bf51-ec13d4fdaa39" />

to this 

<img width="1111" height="152" alt="Image" src="https://github.com/user-attachments/assets/b5a82ed1-11bc-4f37-99c3-0f780e95aef8" />

**Comment by stevezau** [comment]
The app does have a progress bar is you are in a terminal.. 

How are you running ffmpeg.. the 2nd image?

**Comment by issaci22** [comment]
The second one was just on the computer so that I could screenshot it. Nvm I'll check the terminal

**Comment by stevezau** [comment]
Like i said earlier if you login to the docker and run the container from terminal OR if its running already do docker logs -f <container> 

it should show a progress bar at the bottom

**Comment by issaci22** [comment]
Doing docker logs -f shows the same thing, where it updates every line. But I don't care anymore as long as I can see some sort of progress. Thank you for all your help, man. Awesome script 

<img width="743" height="1136" alt="Image" src="https://github.com/user-attachments/assets/633157e1-47cc-49b8-9f7d-b8c3cf305a6a" />

**Comment by stevezau** [comment]
yeah not sure.. it will def show a progress bar on the terminal.. if you run it from there.. or maybe try attach to it. 

docker attach

**Comment by stevezau** [comment]
can we close this issue now @IssacI19 ?
